---
- name: A simple playbook file
  hosts: thename
  vars:
    - ayana2: 24
  tasks:

    - name: Print a sample message
      debug:
        msg: Hello World. Welcome to Ansible playbooks!

    - name: using variables
      debug:
        msg: ayana's age. ayana age is {{ ayana }}
    

    - name: varible2
      debug:
        msg: "ayana's age. ayana age is {{ ayana2 }}"
      when: ayana2 == "26"
