---
- name: A simple playbook file
  hosts: thename
  vars:
    ayana: 24
  tasks:

    - name: Print a sample message
      debug:
        msg: "Hello World. Welcome to Ansible playbooks!"

    - name: using variables
      debug:
        msg: "Ayana's age. Ayana's age is {{ ayana }}"

    - name: Install multiple software
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - samba
        - vsftpd
