---
# tasks file for apache  


- name: Install specific version of Apache
  yum:
    name: httpd
    state: present

- name: Enable service to start on boot up
  service:
    name: httpd
    state: started


